version: 2.1
jobs:
  run_aye:
    working_directory: ~/
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: node index.js

workflows:
  build_tests:
    jobs:
     - run_aye     
